# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailid',
        ),
    ]
